service: nuxt-serverless # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  memorySize: 1024   # Overwrite the default memory size. Default is 1024
  timeout: 300

package:
  include:
    - nuxt.config.js
    - serverless.yml
  exclude:
    - tests/**
    - src/**

functions:
  nuxtRenderer:
    handler: handler.render
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "sandrasoft.com" # Specify a new domain name to be created
    stage: develop
    # certificateName: "*.mydomain.com" # Enter the Certificate name with that domain
    createRoute53Record: true
